name: Master Build

on: workflow_dispatch
#  schedule:
#    - cron: '30 1 * * *'

jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install webapp
        run: git clone -b master https://github.com/nsqr-nz/open-suite-webapp.git open-suite-webapp
      - name: move to the right place
        run: mkdir -p open-suite-webapp/modules/axelor-open-suite && ls | grep -v open-suite-webapp | xargs -I{} mv {} open-suite-webapp/modules/axelor-open-suite
      - name: Grant execute permission for gradlew
        run: chmod +x open-suite-webapp/gradlew
      - name: Build without tests
        run: cd open-suite-webapp && ./gradlew -xtest clean build
      - name: Run tests
        run: cd open-suite-webapp && ./gradlew test
      - name: Read version file
        id: getversion
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      - name: Build Docker
        run: cd open-suite-webapp && docker build --platform linux/amd64 -t nsqr/nsqr-nz-axelor:v${{ steps.getversion.outputs.version }} .
      - name: Check docker images
        run: docker images
      - name: docker login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASS }}
      - name: docker push
        run: docker push nsqr/nsqr-nz-axelor:v${{ steps.getversion.outputs.version }}
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASS }}
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          images: my-docker-hub-namespace/my-docker-hub-repository
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

